# event: [is_hit, at_bat, pa]
from typing import List

new_event_to_pitchers_dict: dict = {"Walk": [0, 0, 1], "Single": [1, 1, 1], "Forceout": [0, 1, 1],
                                    "Groundout": [0, 1, 1],
                                    "Flyout": [0, 1, 1], "Strikeout": [0, 1, 1], "Double": [1, 1, 1],
                                    "Lineout": [0, 1, 1],
                                    "Sac Bunt": [0, 0, 1],
                                    "Bunt Pop Out": [0, 1, 1], "Home Run": [1, 1, 1], "Pop Out": [0, 1, 1],
                                    "Field Error": [0, 0, 0],
                                    "Hit By Pitch": [0, 0, 1],
                                    "Grounded Into DP": [0, 1, 1], "Caught Stealing 2B": [0, 0, 0], "Triple": [1, 1, 1],
                                    "Intent Walk": [0, 0, 1],
                                    "Fielders Choice Out": [0, 0, 1], "Bunt Groundout": [0, 1, 1],
                                    "Double Play": [0, 1, 1],
                                    "Sac Fly": [0, 0, 1], "Pickoff Caught Stealing 2B": [0, 0, 0],
                                    "Strikeout Double Play": [0, 1, 1],
                                    "Caught Stealing Home": [0, 0, 0], "Fielders Choice": [0, 0, 0],
                                    "Runner Out": [0, 0, 0],
                                    "Pickoff 1B": [0, 0, 0],
                                    "Sac Fly Double Play": [0, 1, 1], "Batter Out": [0, 1, 1],
                                    "Caught Stealing 3B": [0, 0, 0],
                                    "Wild Pitch": [0, 0, 0], "Pickoff Caught Stealing 3B": [0, 0, 0],
                                    "Pickoff 2B": [0, 0, 0],
                                    "Pickoff 3B": [0, 0, 0], "Pickoff Caught Stealing Home": [0, 0, 0],
                                    "Catcher Interference": [0, 0, 1],
                                    "Pitching Substitution": [0, 0, 0], "Stolen Base 2B": [0, 0, 0],
                                    "Triple Play": [0, 1, 1],
                                    "Defensive Switch": [0, 0, 0], "Balk": [0, 0, 0], "Defensive Sub": [0, 0, 0],
                                    "Runner Double Play": [0, 0, 0],
                                    "Sac Bunt Double Play": [0, 1, 1], "Pickoff Error 3B": [0, 0, 0], "etc": [0, 0, 0],
                                    "Passed Ball": [0, 0, 0],
                                    "Strikeout Triple Play": [0, 1, 1], "Bunt Lineout": [0, 1, 1],
                                    "Pickoff Error 2B": [0, 0, 0],
                                    "Stolen Base 3B": [0, 0, 0], "Pickoff Error 1B": [0, 0, 0], "Field Out": [0, 1, 1],
                                    "Defensive Indiff": [0, 0, 0], "Injury": [0, 0, 0], "Other Advance": [0, 0, 0],
                                    "Stolen Base Home": [0, 0, 0],
                                    "Game Advisory": [0, 0, 0], "Error": [0, 0, 0], "Ejection": [0, 0, 0],
                                    "Offensive Substitution": [0, 0, 0],
                                    "Cs Double Play": [0, 1, 1]
                                    }

pitcher_primary_position_abbreviation = ("sp", "cp", "p")

pitchers: List = ['uid', 'player_uid', 'season', 'team_uid', 'team_name', 'name', 'birthday', 'height', 'weight',
                  'position', 'left_hit_num', 'right_hit_num', 'left_twob_hit_num', 'right_twob_hit_num',
                  'left_threeb_hit_num', 'right_threeb_hit_num', 'left_hr_num', 'right_hr_num', 'left_pa_num',
                  'right_pa_num', 'left_er', 'right_er', 'left_not_my_er', 'right_not_my_er', 'left_game_num',
                  'right_game_num', 'left_bb_num', 'right_bb_num', 'left_ao_num', 'right_ao_num', 'left_dp_num',
                  'right_dp_num', 'left_ibb_num', 'right_ibb_num', 'player_weather_tmi', 'average',
                  'standard_deviation', 'education', 'win_num', 'lose_num', 'hold_num', 'save_num', 'creater',
                  'updater', 'create_time', 'update_time', 'primary_position_type', 'primary_position_abbreviation',
                  'ct_num', 'balk_num', 'pickoff_catch_num', 'pickoff_num', 'right_throw_ball_num',
                  'left_throw_ball_num', 'left_inning_num', 'right_inning_num', 'league', 'left_k_num', 'right_k_num',
                  'left_rbi_num', 'right_rbi_num', 'left_go_num', 'right_go_num']

event_pitchers_to_pitchers_convert_dict: dict = \
    {"Walk": ['left_bb_num', 'right_bb_num'], "Single": ['left_hit_num', 'right_hit_num'],
     "Forceout": ['left_out_num', 'right_out_num'],
     "Groundout": ['left_out_num', 'right_out_num', 'left_go_num', 'right_go_num'],
     "Flyout": ['left_out_num', 'right_out_num', 'left_ao_num', 'right_ao_num'],
     "Strikeout": ['left_out_num', 'right_out_num', 'left_k_num', 'right_k_num'],
     "Double": ['left_hit_num', 'right_hit_num', 'left_twob_hit_num', 'right_twob_hit_num'],
     "Lineout": ['left_out_num', 'right_out_num'],
     "Sac Bunt": [],
     "Bunt Pop Out": ['left_out_num', 'right_out_num'],
     "Home Run": ['left_hit_num', 'right_hit_num', 'left_hr_num', 'right_hr_num', 'left_pa_num',
                  'right_pa_num', 'left_er', 'right_er', 'left_not_my_er', 'right_not_my_er'],
     "Pop Out": ['left_out_num', 'right_out_num'],
     "Field Error": [],
     "Hit By Pitch": [],
     "Grounded Into DP": ['left_dp_num', 'right_dp_num', ], "Caught Stealing 2B": ['pickoff_num', 'pickoff_catch_num'],
     "Triple": ['left_hit_num', 'right_hit_num', 'left_threeb_hit_num', 'right_threeb_hit_num', ],
     "Intent Walk": ['left_ibb_num', 'right_ibb_num', 'left_out_num', 'right_out_num'],
     "Fielders Choice Out": ['left_out_num', 'right_out_num'], "Bunt Groundout": ['left_out_num', 'right_out_num'],
     "Double Play": ['left_out_num', 'right_out_num', 'left_dp_num', 'right_dp_num'],
     "Sac Fly": ['left_out_num', 'right_out_num'], "Pickoff Caught Stealing 2B": ['pickoff_num', 'pickoff_catch_num'],
     "Strikeout Double Play": ['left_k_num', 'right_k_num', 'left_out_num', 'right_out_num'],
     "Caught Stealing Home": ['pickoff_num', 'pickoff_catch_num'], "Fielders Choice": [],
     "Runner Out": [],
     "Pickoff 1B": ['pickoff_num'],
     "Sac Fly Double Play": ['left_ao_num', 'right_ao_num', 'left_out_num', 'right_out_num'],
     "Batter Out": ['left_out_num', 'right_out_num'],
     "Caught Stealing 3B": ['pickoff_num', 'pickoff_catch_num'],
     "Wild Pitch": ['left_wild_pitch_num', 'right_wild_pitch_num'],
     "Pickoff Caught Stealing 3B": ['pickoff_num', 'pickoff_catch_num'],
     "Pickoff 2B": ['pickoff_num'],
     "Pickoff 3B": ['pickoff_num'], "Pickoff Caught Stealing Home": ['pickoff_num', 'pickoff_catch_num'],
     "Catcher Interference": [],
     "Pitching Substitution": [], "Stolen Base 2B": ["get_stolen_num"],
     "Triple Play": ['left_out_num', 'right_out_num'],
     "Defensive Switch": [], "Balk": ["balk_num"],
     "Defensive Sub": [],
     "Runner Double Play": [],
     "Sac Bunt Double Play": ['left_out_num', 'right_out_num'], "Pickoff Error 3B": ["pickoff_num"],
     "etc": [],
     "Passed Ball": [],
     "Strikeout Triple Play": ['left_out_num', 'right_out_num', 'left_out_num', 'right_out_num'],
     "Bunt Lineout": ['left_out_num', 'right_out_num'],
     "Pickoff Error 2B": ["pickoff_num"],
     "Stolen Base 3B": ["get_stolen_num"], "Pickoff Error 1B": ["pickoff_num"],
     "Field Out": ['left_out_num', 'right_out_num'],
     "Defensive Indiff": [], "Injury": [],
     "Other Advance": [],
     "Stolen Base Home": ["get_stolen_num"],
     "Game Advisory": [], "Error": [], "Ejection": [],
     "Offensive Substitution": [],
     "Cs Double Play": ['left_out_num', 'right_out_num']}

left_event_pitchers_to_pitchers_convert_dict: dict = \
    {"Walk": ['left_bb_num'], "Single": ['left_hit_num'],
     "Forceout": ['left_out_num'],
     "Groundout": ['left_out_num', 'left_go_num', ],
     "Flyout": ['left_out_num', 'left_ao_num'],
     "Strikeout": ['left_out_num', 'left_k_num'],
     "Double": ['left_hit_num', 'left_twob_hit_num', ],
     "Lineout": ['left_out_num'],
     "Sac Bunt": [],
     "Bunt Pop Out": ['left_out_num'],
     "Home Run": ['left_hit_num', 'left_hr_num', 'left_pa_num', 'left_er', 'left_not_my_er', ],
     "Pop Out": ['left_out_num'],
     "Field Error": [],
     "Hit By Pitch": [],
     "Grounded Into DP": ['left_dp_num'], "Caught Stealing 2B": ['pickoff_num', 'pickoff_catch_num'],
     "Triple": ['left_hit_num', 'left_threeb_hit_num', ],
     "Intent Walk": ['left_ibb_num', 'left_out_num', ],
     "Fielders Choice Out": ['left_out_num'], "Bunt Groundout": ['left_out_num'],
     "Double Play": ['left_out_num', 'left_dp_num'],
     "Sac Fly": ['left_out_num'], "Pickoff Caught Stealing 2B": ['pickoff_num', 'pickoff_catch_num'],
     "Strikeout Double Play": ['left_k_num', 'left_out_num'],
     "Caught Stealing Home": ['pickoff_num', 'pickoff_catch_num'], "Fielders Choice": [],
     "Runner Out": [],
     "Pickoff 1B": ['pickoff_num'],
     "Sac Fly Double Play": ['left_ao_num', 'left_out_num', ],
     "Batter Out": ['left_out_num'],
     "Caught Stealing 3B": ['pickoff_num', 'pickoff_catch_num'],
     "Wild Pitch": ['left_wild_pitch_num'],
     "Pickoff Caught Stealing 3B": ['pickoff_num', 'pickoff_catch_num'],
     "Pickoff 2B": ['pickoff_num'],
     "Pickoff 3B": ['pickoff_num'], "Pickoff Caught Stealing Home": ['pickoff_num', 'pickoff_catch_num'],
     "Catcher Interference": [],
     "Pitching Substitution": [], "Stolen Base 2B": ["get_stolen_num"],
     "Triple Play": ['left_out_num'],
     "Defensive Switch": [], "Balk": ["balk_num"],
     "Defensive Sub": [],
     "Runner Double Play": [],
     "Sac Bunt Double Play": ['left_out_num'], "Pickoff Error 3B": ["pickoff_num"],
     "etc": [],
     "Passed Ball": [],
     "Strikeout Triple Play": ['left_out_num', 'left_out_num'],
     "Bunt Lineout": ['left_out_num'],
     "Pickoff Error 2B": ["pickoff_num"],
     "Stolen Base 3B": ["get_stolen_num"], "Pickoff Error 1B": ["pickoff_num"],
     "Field Out": ['left_out_num'],
     "Defensive Indiff": [], "Injury": [],
     "Other Advance": [],
     "Stolen Base Home": ["get_stolen_num"],
     "Game Advisory": [], "Error": [], "Ejection": [],
     "Offensive Substitution": [],
     "Cs Double Play": ['left_out_num']}

right_event_pitchers_to_pitchers_convert_dict: dict = \
    {"Walk": ['right_bb_num'], "Single": ['right_hit_num'],
     "Forceout": ['right_out_num'],
     "Groundout": ['right_out_num', 'right_go_num'],
     "Flyout": ['right_out_num', 'right_ao_num'],
     "Strikeout": ['right_out_num', 'right_k_num'],
     "Double": ['right_hit_num', 'right_twob_hit_num'],
     "Lineout": ['right_out_num'],
     "Sac Bunt": [],
     "Bunt Pop Out": ['right_out_num'],
     "Home Run": ['right_hit_num', 'right_hr_num',
                  'right_pa_num', 'right_er', 'right_not_my_er'],
     "Pop Out": ['right_out_num'],
     "Field Error": [],
     "Hit By Pitch": [],
     "Grounded Into DP": ['right_dp_num', ], "Caught Stealing 2B": ['pickoff_num', 'pickoff_catch_num'],
     "Triple": ['right_hit_num', 'right_threeb_hit_num', ],
     "Intent Walk": ['right_ibb_num', 'right_out_num'],
     "Fielders Choice Out": ['right_out_num'], "Bunt Groundout": ['right_out_num'],
     "Double Play": ['right_out_num', 'right_dp_num'],
     "Sac Fly": ['right_out_num'], "Pickoff Caught Stealing 2B": ['pickoff_num', 'pickoff_catch_num'],
     "Strikeout Double Play": ['right_k_num', 'right_out_num'],
     "Caught Stealing Home": ['pickoff_num', 'pickoff_catch_num'], "Fielders Choice": [],
     "Runner Out": [],
     "Pickoff 1B": ['pickoff_num'],
     "Sac Fly Double Play": ['right_ao_num', 'right_out_num'],
     "Batter Out": ['right_out_num'],
     "Caught Stealing 3B": ['pickoff_num', 'pickoff_catch_num'],
     "Wild Pitch": ['right_wild_pitch_num'],
     "Pickoff Caught Stealing 3B": ['pickoff_num', 'pickoff_catch_num'],
     "Pickoff 2B": ['pickoff_num'],
     "Pickoff 3B": ['pickoff_num'], "Pickoff Caught Stealing Home": ['pickoff_num', 'pickoff_catch_num'],
     "Catcher Interference": [],
     "Pitching Substitution": [], "Stolen Base 2B": ["get_stolen_num"],
     "Triple Play": ['right_out_num'],
     "Defensive Switch": [], "Balk": ["balk_num"],
     "Defensive Sub": [],
     "Runner Double Play": [],
     "Sac Bunt Double Play": ['right_out_num'], "Pickoff Error 3B": ["pickoff_num"],
     "etc": [],
     "Passed Ball": [],
     "Strikeout Triple Play": ['right_out_num', 'right_out_num'],
     "Bunt Lineout": ['right_out_num'],
     "Pickoff Error 2B": ["pickoff_num"],
     "Stolen Base 3B": ["get_stolen_num"], "Pickoff Error 1B": ["pickoff_num"],
     "Field Out": ['right_out_num'],
     "Defensive Indiff": [], "Injury": [],
     "Other Advance": [],
     "Stolen Base Home": ["get_stolen_num"],
     "Game Advisory": [], "Error": [], "Ejection": [],
     "Offensive Substitution": [],
     "Cs Double Play": ['right_out_num']}

case_dict = {"left_count_num": 0, "right_count_num": 0, "left_hit_num": 0, "right_hit_num": 0,
             "left_twob_hit_num": 0, "right_twob_hit_num": 0, "left_threeb_hit_num": 0,
             "right_threeb_hit_num": 0,
             "left_hr_num": 0, "right_hr_num": 0, "left_pa_num": 0, "right_pa_num": 0, "left_er": 0,
             "right_er": 0, "left_not_my_er": 0, "right_not_my_er": 0, "left_game_num": 0, "right_game_num": 0,
             "left_bb_num": 0, "right_bb_num": 0, "left_ao_num": 0, "right_ao_num": 0, "left_dp_num": 0,
             "right_dp_num": 0, "left_ibb_num": 0, "right_ibb_num": 0, "left_count_num": 0,
             "right_count_num": 0,
             "win_num": 0, "lose_num": 0, "save_num": 0, "hold_num": 0, "left_out_num": 0, "right_out_num": 0,
             "pickoff_num": 0, "pickoff_catch_num": 0, "left_go_num": 0, "right_go_num": 0, "left_k_num": 0,
             "right_k_num": 0, "get_stolen_num": 0, "left_wild_pitch_num": 0, "right_wild_pitch_num": 0}
